name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: install dependencies
      run: | 
        pip install poetry
        make install
        make build
        make force-reinstall

    - name: Run linter
      run: make lint
    - name: Run tests
      run: make test
    - name: Code Climate Coverage Action
      uses: paambaati/codeclimate-action@v4.0.0
